# This is a basic workflow to help you get started with Actions

name: Label trigger

# Controls when the workflow will run
on:
  pull_request:
    branches: [ '*' ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "add-comment"
  add-comment:
    if: contains(github.event.pull_request.labels.*.name, 'add-comment')
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      issues: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v2
        issue-number: ${{ github.event.pull_request.number }}
        with:
          body: |
            This comment was written by a bot!
          reactions: rocket
