# This is a basic workflow to help you get started with Actions

name: Manage schema

# Controls when the workflow will run
on:
  pull_request:
    types: [ labeled ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "add-comment"
  add-comment:
    if: ${{ github.event.label.name == 'diff-schema' }}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      issues: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Create comment
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            This comment was written by a bot!
          reactions: rocket
